apiVersion: v1
kind: Namespace
metadata:
  name: mcp-server-calculator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-calculator
  namespace: mcp-server-calculator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server1
  template:
    metadata:
      labels:
        app: mcp-server1
    spec:
      containers:
      - name: mcp-server1
        image: ziyue123/mcp-server:latest
        ports:
        - containerPort: 9000
      serviceAccountName: calculator-sa
---
apiVersion: v1
kind: Service
metadata:
  name: server1-svc
  namespace: mcp-server-calculator-system
spec:
  selector:
    app: mcp-server1
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calculator-sa
  namespace: mcp-server-calculator-system
